### ISSUE TITLE
Black and flake8 setting inconsistency

### ISSUE THREAD

**Issue by ConorFWild** [DiamondLightSource/python3-pip-skeleton-cli#55] opened 2023-01-12 10:30 UTC
flake8 defaults to line length 79 without options, while black defaults to line length 88, which makes precomit liable to fail. This could be fixed by editing the pre-commit yaml to:

  - repo: local
    hooks:
      - id: black
        name: Run black
        stages: [commit]
        language: system
        entry: black --check --diff --line-length=79
        types: [python]

or 

      - id: flake8
        name: Run flake8
        stages: [commit]
        language: system
        entry: flake8 --max-line-length=88
        types: [python]

This could also induce changes in the setting json such as:

    "python.linting.flake8Args": [
        "--max-line-length=79"
    ],

**Comment by gilesknap** [comment] 2023-01-12 11:26
I was under the impression we already had this covered.

I'll take a look.

**Comment by gilesknap** [comment] 2023-01-18 09:21
The vscode settings should be updated.
I have 
```json
"python.linting.flake8Args": [
  "--max-line-length=88"
]
```
in my user settings which is why this works for me.

Regarding the precommit settings I take your point but for some reason this works for me as is. @coretl do you know why this is the case?

**Comment by GDYendell** [comment] 2023-01-18 09:38
I think `flake8` with no arguments obeys the config in setup.cfg / pyproject.toml. It seems to work both for linting in vscode and when run in a terminal. If I take out the config from setup.cfg it complains about all my lines between 79 and 88 characters.

**Comment by coretl** [comment] 2023-01-18 09:49
@GDYendell does that also work with the latest skeleton where settings have been moved to pyproject.toml? We use a flake8 plugin to read settings like this from pyproject.toml rather than setup.cfg, but it may have broken...

**Comment by GDYendell** [comment] 2023-01-18 09:59
Checked in python3-pip-skeleton. It does as long as you have Flake8-pyproject installed in your venv.

**Comment by gilesknap** [comment] 2023-01-18 10:21
@GDYendell @thomascobb thanks both. I've just confirmed that removing my user setting in vscode also still works.

Closing this ticket as flake8 is automatically taking on line length 88 via Flake8-pyproject.

**Closed by gilesknap** 2023-01-18 10:21 UTC
