### ISSUE TITLE
Incorrect naming / link generating during adoption

### ISSUE THREAD

**Issue by JoshuaAppleby** [DiamondLightSource/python3-pip-skeleton-cli#83] opened 2023-04-12 13:33 UTC
In docs/developer/how-to/pin-requirements.rst, when adopting skeleton for pytac, python3-pip-skeleton-cli is being replaced with the new project name incorrectly here, meaning that link checks fail as project-cli does not exist.

Changed: 
```
For example take a look at the release page for python3-pip-skeleton-cli here:
https://github.com/DiamondLightSource/python3-pip-skeleton-cli/releases/tag/3.3.0
```

To:
```
For example take a look at the release page for pytac-cli here:
https://github.com/DiamondLightSource/pytac-cli/releases/tag/3.3.0
```

**Comment by gilesknap** [comment] 2023-04-12 13:55
Yep I have seen this issue too. Get spammed by all my skeleton based projects accordingly :-)

**Comment by evalott100** [comment] 2023-04-13 08:01
This has already been fixed on main with the addition of `pin-requirements.rst` to `IGNORE_FILES` in `__main__.py`, however this fix is not present in the latest release `3.3.0`.

I tested locally on the  `HLA-610-add-I04-ring-modes` branch on  pytac and the problem wasn't reproduces.

@gilesknap time for another release?

**Comment by gilesknap** [comment] 2023-04-13 08:05
@evalott100 yes I think this warrants a new release!

**Comment by evalott100** [comment] 2023-04-13 08:07
Shall I do this?

**Comment by gilesknap** [comment] 2023-04-13 08:08
Yes please :-)

**Closed** 2023-04-13 08:17 UTC
